import re
from .utils import get_base_type


def map_drf_type_to_openapi(drf_type):
    """Maps Django/DRF field types to OpenAPI types."""
    drf_type = drf_type.lower()

    if "int" in drf_type:
        return {"type": "integer"}
    elif "float" in drf_type or "decimal" in drf_type:
        return {"type": "number"}
    elif "bool" in drf_type:
        return {"type": "boolean"}
    elif "list" in drf_type:
        return {"type": "array", "items": {"type": "string"}}
    elif "dict" in drf_type or "json" in drf_type:
        return {"type": "object"}
    elif "datetime" in drf_type:
        return {"type": "string", "format": "date-time"}
    elif "date" in drf_type:
        return {"type": "string", "format": "date"}
    elif "uuid" in drf_type:
        return {"type": "string", "format": "uuid"}
    elif "email" in drf_type:
        return {"type": "string", "format": "email"}

    return {"type": "string"}


def generate_openapi_spec(specs, serializers_map):
    """Converts GenDoc scan results to OpenAPI 3.0 dictionary."""
    openapi = {
        "openapi": "3.0.2",
        "info": {
            "title": "Generated API Documentation",
            "version": "1.0.0",
            "description": "Auto-generated by GenDoc Static Analysis",
            "contact": {"name": "GenDoc"},
        },
        "paths": {},
        "components": {"schemas": {}},
    }

    # 1. Build Components (Schemas)
    for ser_name, ser_details in serializers_map.items():
        if not ser_name:
            continue

        schema = {"type": "object", "properties": {}, "required": []}

        for field_name, field_info in ser_details.get("fields", {}).items():
            field_type_raw = field_info.get("type", "string")
            props = field_info.get("props", [])

            base_type = get_base_type(field_type_raw)
            field_schema = {}

            if base_type in serializers_map:
                field_schema = {"$ref": f"#/components/schemas/{base_type}"}
                if field_type_raw.startswith("List["):
                    field_schema = {"type": "array", "items": field_schema}
            else:
                field_schema = map_drf_type_to_openapi(field_type_raw)
                if (
                    field_type_raw.startswith("List[")
                    and field_schema.get("type") != "array"
                ):
                    field_schema = {"type": "array", "items": {"type": "string"}}

            if "ReadOnly" in props:
                field_schema["readOnly"] = True
            if "WriteOnly" in props:
                field_schema["writeOnly"] = True
            if "Nullable" in props:
                field_schema["nullable"] = True
            if "Required" in props:
                schema["required"].append(field_name)

            schema["properties"][field_name] = field_schema

        if not schema["required"]:
            del schema["required"]

        openapi["components"]["schemas"][ser_name] = schema

    # 2. Build Paths
    for spec in specs:
        path = spec.get("path", "/")
        # Convert Django URL params <type:name> or <name> to OpenAPI {name}
        openapi_path = re.sub(r"<[^:>]+:([^>]+)>", r"{\1}", path)
        openapi_path = re.sub(r"<([^>]+)>", r"{\1}", openapi_path)

        if openapi_path not in openapi["paths"]:
            openapi["paths"][openapi_path] = {}

        for method, details in spec.get("methods", {}).items():
            method_lower = method.lower()

            operation = {
                "summary": f"{method} {path}",
                "description": spec.get("doc", "").strip(),
                "responses": {},
                "tags": [spec.get("view", "Default")],
            }

            path_params = re.findall(r"{([^}]+)}", openapi_path)
            if path_params:
                operation["parameters"] = []
                for param in path_params:
                    operation["parameters"].append(
                        {
                            "name": param,
                            "in": "path",
                            "required": True,
                            "schema": {"type": "string"},
                        }
                    )

            # Request Body
            req_ser = details.get("request")
            if req_ser and req_ser not in ["None", "Not required", "NoBody"]:
                base_req = get_base_type(req_ser)
                schema_ref = None

                if base_req in serializers_map:
                    schema_ref = {"$ref": f"#/components/schemas/{base_req}"}
                elif "RawBody" in req_ser:
                    schema_ref = {"type": "object", "description": "Raw JSON Body"}

                if schema_ref:
                    if req_ser.startswith("List["):
                        schema_ref = {"type": "array", "items": schema_ref}

                    operation["requestBody"] = {
                        "content": {"application/json": {"schema": schema_ref}}
                    }

            # Responses
            res_details = details.get("response_details")
            if res_details:
                for status, info in res_details.items():
                    ser = info.get("serializer")
                    response_obj = {"description": f"Status {status}"}

                    if ser and ser != "Unknown" and ser != "NoContent":
                        base_res = get_base_type(ser)
                        schema_ref = None

                        if base_res in serializers_map:
                            schema_ref = {"$ref": f"#/components/schemas/{base_res}"}
                        elif "Dynamic" in ser or "Object" in ser:
                            schema_ref = {"type": "object"}

                        if schema_ref:
                            if ser.startswith("List["):
                                schema_ref = {"type": "array", "items": schema_ref}

                            response_obj["content"] = {
                                "application/json": {"schema": schema_ref}
                            }

                    operation["responses"][status] = response_obj
            else:
                res_str = details.get("response", "None")
                operation["responses"]["200"] = {"description": f"Success: {res_str}"}

            openapi["paths"][openapi_path][method_lower] = operation

    return openapi
